#NoEnv
#SingleInstance Force
SendMode Input
SetWorkingDir %A_ScriptDir%

; Automatically append a matching XML closing tag after completing an opening tag.
; Example: typing "<note>" produces "<note></note>" and places the caret between them.

global gXmlAutoClose_ListenActive := false
global gXmlAutoClose_Suppress := false

~<::  ; Fire whenever a literal "<" is typed
    if (gXmlAutoClose_Suppress)
        return  ; ignore synthetic "<" events generated by this helper
    if (gXmlAutoClose_ListenActive)
        return  ; avoid re-entrancy while we are already tracking a tag

    gXmlAutoClose_ListenActive := true
    Input, __XmlTagBody, V, {>}{Esc}{BackSpace}{Enter}{Tab}
    gXmlAutoClose_ListenActive := false

    if (ErrorLevel != "EndKey:>")
        return  ; we only care about true opening tags that end with ">"

    __XmlTagBody := Trim(__XmlTagBody)
    if (__XmlTagBody = "")
        return

    ; Ignore closing tags like "</note>" and self-closing tags such as "<note/>".
    if (SubStr(__XmlTagBody, 1, 1) = "/")
        return
    if RegExMatch(__XmlTagBody, "/\s*$")
        return

    if !RegExMatch(__XmlTagBody, "^[A-Za-z_:][A-Za-z0-9._:-]*", __XmlTagName)
        return  ; no valid tag name detected at the start

    gXmlAutoClose_Suppress := true
    SendInput, </%__XmlTagName%>
    gXmlAutoClose_Suppress := false

    __XmlCursorShift := StrLen(__XmlTagName) + 3  ; "</" + ">" = 3 characters
    if (__XmlCursorShift > 0)
        SendInput, {Left %__XmlCursorShift%}
return
