#Requires AutoHotkey v2.0
; ====================================================================
; LARGE TEXT HOTSTRING: role-task-constraint
; ====================================================================
; Note: SaveClipboard() and RestoreClipboard() are provided by environment.ahk

; Function for role-task-constraint template
RoleTaskConstraint() {
    clipSaved := SaveClipboard()
    dq := Chr(34)
    text := ""
    clipSaved := SaveClipboard()
    dq := Chr(34)
    text := ""
    text .= "ROLE:`n"
    text .= "You are an autonomous debugging engineer tasked with supervising a live codebase recovery and stabilization operation.`n"
    text .= "`n"
    text .= "TASK:`n"
    text .= "Execute a structured three-phase maintenance cycle followed by continued root-cause debugging.  `n"
    text .= "Each phase must complete fully before moving to the next. Persist findings and context between phases.  `n"
    text .= "When the final phase concludes, summarize all findings and provide next-step recommendations.`n"
    text .= "`n"
    text .= "---`n"
    text .= "`n"
    text .= "PHASE A: CODEBASE COMPLETENESS REVIEW`n"
    text .= "Objective:`n"
    text .= "- Examine the full codebase for structural completeness and consistency.`n"
    text .= "- Identify missing modules, incomplete logic paths, broken imports, or placeholder sections.`n"
    text .= "- Verify that each functional component referenced in the CLI or agent orchestration layer exists and is callable.`n"
    text .= "`n"
    text .= "Steps:`n"
    text .= "1. Map top-level structure of the project.`n"
    text .= "2. Compare module references against actual implementations.`n"
    text .= "3. Record missing or stale components.`n"
    text .= "4. Output a concise table of findings before proceeding to Phase B.`n"
    text .= "`n"
    text .= "Deliverable:`n"
    text .= "Structured section titled " . dq . "Codebase Review Summary" . dq . ".`n"
    text .= "`n"
    text .= "---`n"
    text .= "`n"
    text .= "PHASE B: DOCUMENTATION ALIGNMENT AND SYNCHRONIZATION`n"
    text .= "Objective:`n"
    text .= "- Compare coordination and planning files (Agents.md, TODO.md, PLAN.md, or similar) with the actual implementation state.`n"
    text .= "- Identify outdated directives, incorrect dependencies, or unfulfilled TODO items.`n"
    text .= "- Suggest precise updates or replacements for each discrepancy.`n"
    text .= "- Treat documentation edits as proposed diffs, not direct changes.`n"
    text .= "`n"
    text .= "Steps:`n"
    text .= "1. Parse documentation files for objectives and component references.`n"
    text .= "2. Cross-reference against the codebase from Phase A.`n"
    text .= "3. Generate section-by-section update recommendations.`n"
    text .= "4. Summarize discrepancies and proposed updates.`n"
    text .= "`n"
    text .= "Deliverable:`n"
    text .= "Structured section titled " . dq . "Documentation Sync Report" . dq . ".`n"
    text .= "`n"
    text .= "---`n"
    text .= "`n"
    text .= "PHASE C: ESCALATION AND STAFF ENGINEER HANDOFF`n"
    text .= "Objective:`n"
    text .= "- Identify non-critical but necessary maintenance or refactor tasks for staff engineers.`n"
    text .= "- Categorize by priority and complexity.`n"
    text .= "- Prepare a clear action queue to delegate these tasks while continuing to focus on the root CLI exit issue.`n"
    text .= "`n"
    text .= "Steps:`n"
    text .= "1. Aggregate remaining issues not directly tied to the root bug.`n"
    text .= "2. Classify into:`n"
    text .= "   - Priority 1: Blocking issues`n"
    text .= "   - Priority 2: Maintenance or cleanup`n"
    text .= "   - Priority 3: Documentation or low impact`n"
    text .= "3. Generate escalation list for engineer handoff.`n"
    text .= "`n"
    text .= "Deliverable:`n"
    text .= "Structured section titled " . dq . "Escalation Items" . dq . ".`n"
    text .= "`n"
    text .= "---`n"
    text .= "`n"
    text .= "PHASE D: CONTINUED ROOT CAUSE DEBUGGING`n"
    text .= "Objective:`n"
    text .= "- Resume focus on the original runtime failure: CLI exits immediately after input.`n"
    text .= "- Incorporate findings from earlier phases (e.g., missing handler, outdated doc instruction, configuration mismatch).`n"
    text .= "- Narrow to probable cause and propose fix.`n"
    text .= "- Provide test plan and monitoring strategy.`n"
    text .= "`n"
    text .= "Deliverable:`n"
    text .= "Structured section titled " . dq . "Ongoing Debugging Summary" . dq . ".`n"
    text .= "`n"
    text .= "---`n"
    text .= "`n"
    text .= "CONSTRAINTS:`n"
    text .= "- Execute phases sequentially, not concurrently.`n"
    text .= "- Maintain persistent reasoning memory across turns.`n"
    text .= "- Never discard earlier findings; reference them explicitly when relevant.`n"
    text .= "- Keep responses concise and structured for staff readability.`n"
    text .= "- Do not modify code or documentation directly; report actionable proposals instead.`n"
    text .= "- Avoid speculative explanations unless supported by evidence from context.`n"
    text .= "`n"
    text .= "---`n"
    text .= "`n"
    text .= "OUTPUT FORMAT (FINAL AGGREGATED REPORT):`n"
    text .= "1. Codebase Review Summary`n"
    text .= "2. Documentation Sync Report`n"
    text .= "3. Escalation Items`n"
    text .= "4. Ongoing Debugging Summary`n"
    text .= "5. Next Actions Checklist`n"
    text .= "`n"
    text .= "---`n"
    text .= "`n"
    text .= "SUCCESS CRITERIA:`n"
    text .= "- All four phases completed with traceable reasoning and outputs.`n"
    text .= "- No redundant scanning or hallucinated modules.`n"
    text .= "- Clear and actionable handoff report for staff engineers.`n"
    text .= "- Continued progress on root cause analysis without context loss.`n"
    text .= "`n"
    text .= "---`n"
    text .= "`n"
    text .= "API SETTINGS:`n"
    text .= "reasoning_effort=" . dq . "high" . dq . "`n"
    text .= "verbosity=" . dq . "medium" . dq . "`n"
    SendHotstringText(text)
    RestoreClipboard(clipSaved)
}

Hotstring(":*:role-task-constraint", (*) => SendHotstringText(RoleTaskConstraint()))
